### PR TITLE
feat: GreaterThan supports negative and large numbers

### LINKED ISSUE #162: Extend GreaterThan to support negative numbers
It appears to be quite easy to extend the implementation of `GreaterThan` to also support negative numbers, which would make it significantly more useful.

[Here's my rough implementation](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQQHYBMA0cCiBHAVwEMAbbASQGcAFCS4GYANwFMLKB1ACwhLbgByEGNgAiwAOYNkUKEQCe2ALJEAHtmpF0AGRYAzEXAASLLWMkNsAFSLAScAL5w9UCCDgAiGPLAsAtGAkBJQeANwAUOHevnASMFYslDAAjHAAvHAA4lCmMCxQVlxEqDiqeRgs6AA8ydgATAB8UT4ssfGJMHXpWTlEeQVFJWUsFdV12MlN0a1xCUkAzN3ZufmFxaXl6JVVfrVwk80xsx0ALEu9-WtDm9t7u1MtbXMwAKznKwPrw6M743D3hxm7SSADZ3n1VoMNiMttVdtg-I1IixVJBYHBpj0PldoT9kHAUZtKHBUAQQAAjfLYABCBO+6GJpIpVLgADFbPYMqgWKwoA10uE4CgMFUqNxeCwqsgGuxxXwqtSGvzCTDiXpSJRWgB+NkcuAALkFJLJlKgdKJKDgOvZdgNRqZpvNqrgtOtesNQvwxBIUppyvpxJgUAI2ucGtaHuF1SotHojFYUplgmEopodAYzEliqVTowgeDoaDIbtQrQ1SEMFTsYzCelSZj6fjWZzKrzGILVrDJE1JajVcbmcT7GrTYVLYD7eLOoA8qgR5m5ZLkH7e7P56xFwrsNLIoC4GuBxuePL8a2GcbmVAabnzw78vyMgAKI2s1wgAQm-LIcmURM34nAKgej5HAoj4jqYH-hepoANoALpWi+b4fpe36-oqUGAcBZqiK6oG0mejKflA8GIUKKiqFUYEwQA5HwqBxFwNFwWI1K0fRjHMf6FpYSBSidvxhHQSBWpGpoOj6JWYHKNgAAM3HOrxZrUJBOoqaeE53iRCGiUK4m6AYVHUjJcDyZhQEgSpeFWVBWmkbp+6oOIUgwDIcjyFU6kaLhTRCvqJI8iB-ncryRrBYFZrhaFfkBbyBqxfkYUJZFyVJSFQWpQAlJEmKzs50iyAoVEaRadksfhtnEfBD5wM+nqEKQVQmFoxVJs11Q+QpbZFiwRpCjOTkWK5hUeTYditdYHJGUqfXxflMAAHTLBCnyoE1pgddK2DtdNTTZXuVhQKASiAcEADKkhrQIUFJEdDE1ddQkAAZ+AAJAgSlwDkSQOE9Ro6t98D+QIER7q+bgoaaaFVI9mnETV81uQoC3gyAZ1BoBEhVIdx2nZQF0SGtT3vQIv1KkAA), including the fix from #161.

### PR DESCRIPTION
**Pull request by unional**
Thank you for the idea! @Jcparkyn 🍻

Closes #162

### CODE REVIEW

**Comment by Jcparkyn** [comment]
One issue with this implementation is that `Abs` only works for relatively small numbers that can be represented as tuples (down to -10000 I think). If you keep the result as a string it'll work for much larger numbers, which I think is all the way until JS starts converting them to scientific notation.

**Comment by unional** [comment]
Yep, you are right.

**Comment by unional** [comment]
Another improvement is to move all calculations to the digit array, that means `Add` and `Subtract` can also work on much larger number as long as the result is within `0` to `10000`

**Comment by Jcparkyn** [comment]
@unional I thought you might be interested in what I've been using this for, which is [this](https://github.com/Jcparkyn/type-sort). I also have some ideas for extending it to support non-integers and scientific notation (and maybe an alternate implementation for sorting strings), so I'll try to make a PR if I ever get that working.

**Comment by unional** [comment]
Cool, sounds interesting. :)

**Pull request merged**
