### PR TITLE
fix: Pick and Omit over intersection types

### PR DESCRIPTION
**Pull request by unional**
@dragomirtitian

I get the initial implementation of these `Pick<>` and `Omit<>` from your comment https://github.com/microsoft/TypeScript/issues/28339#issuecomment-463577347

I tried it out and found that the `UnionKeys<>` does not work on intersection types.

Do you see any concern of using `keyof T` over `UnionKeys<>`?

### CODE REVIEW

**Comment by dragomirtitian** [comment]
@unional I am concerned about compiler performance, distributive conditional types tend to cause performance issues with large unions. But other than that it should be fine if `T` is not a union `UnionKeys<T>` will just be `keyof T`.

What do you mean `UnionKeys` does not work with intersections ? [Seems to me it works](https://typescript-play.js.org/#code/C4TwDgpgBAKgjFAvFA3gKCpqAzA9rgLigGdgAnASwDsBzNAXygDJUMsAjAQwC8jTLaDKAB9WWKFzJEqAVwC27CGQZpQkKAFUqFXFQDSEEMQA8MAHxJYUCAA9gEKgBNiUTlRBQA-FADWh3NhW0hAAbkpoquDQegjIWjr6hibwFgD0qVAARHi4mSJZXNx5opmSmUA)

Thanks for the attribution :)

**Comment by unional** [comment]
Thanks. I'm debating whether should the user concern with compiler performance when they choose which type to use. IMO it should be about behavior. Should the user need to know about the gritty detail?
That's why for now I keep the name as `Pick<>` and `Omit<>`, replacing the functionality of the build-in one if user choose to.

It doesn't work on intersection with generics. You can check it out [here](https://typescript-play.js.org/#code/C4TwDgpgBAqgdgSwPZwNIRAZwDwBUB8UAvFLlBAB7ARwAmmUAhnCFAPxQDWGSAZqVABcUOBABuEAE4AoaaEhQACggDGnAEx4ANFFTkqNerEQp0WPPkIkylanQZkOAbygBtRVARxdAXWG53HygAXyERcSlZeWgAMSQkYigXRmFMYEkvAHMdACNU9KyQ6V4AVzgVYGRvXniLAAovMBLgYWU1TTiEgDJSHQByRj78AEphMSQEWiTpYOkgA)

**Comment by dragomirtitian** [comment]
Performance isn't an issue until it is. But I agree functionality is more important.

The reason it does not work on intersection with generics is that conditional types with unresolved type parameters are not expanded, so `UnionKeys<T & Foo> is opaque to the compiler inside the generic function.


One change that can improve this situation is to add `keyof T` to `UnionKeys` as a fallback so at least for generics you are not worse of than before.

```ts 
type UnionKeys<T> = keyof T | (T extends any ? keyof T : never)

```
[sample] (https://typescript-play.js.org/#code/C4TwDgpgBAqgdgSwPZwNIRAZwDwBUB8UAvFANYZIBmUuUAPlABS0QAewEcAJplAIZwQUAPxkK1WgC4ocCADcIAJwCUAKFWhIUAAoIAxqQBMeADRRUUNh2694yNBhwFCJFu048aIqAG8oAbW0oBDhzAF1pXECwqABfKGlZBUV1TWgAMSQkYl9+aUxgRRCAczMAI3zCkrjVSgBXOD1geyhKLLx8RhCwOuBpXQNjTOyAMhozAHI+CfxlaTkkBC5fVVjVIA)

**Comment by unional** [comment]
Thanks, that works! 🌷 

Agree with what you said. If we have a way to distinguish between normal unions and discriminative unions, we can fall back to the more performant way, but force user to use a different `Pick<>` and `Omit<>` because the subject is a discriminative union is a hard call. I can see a lot of frustration and scratching heads because of that.

On a side note, what do you think about:
```ts
type UnionKeys<T> = keyof T | (T extends any ? keyof T : never)
// vs
type UnionKeys<T> = keyof T | (T extends T ? keyof T : never)
```

**Comment by dragomirtitian** [comment]
I used to use `T extends any` (still do out of habit sometimes), but it was pointed out to me in an issue i filed (when `extends any` was not working as expected in `StrictUnion` https://github.com/microsoft/TypeScript/issues/30569) that `any` is 'weird' (I think that should be in the doc "Any is weird" 😂) and is best avoided even in conditional types. So I would go with `T extends T` or `T extends unknown`.

**Comment by unional** [comment]
Got it.
I still wonder if `Pick<>` and `Omit<>` should use `UnionKeys<>`.
I understand that `Pick<>` and `Omit<>` should use conditional type so that it can be distributed to the unions.
But I'm not sure about "distributing" `K` over the `keyof T`, can't wrap my mind around it.

Based on this [example](https://typescript-play.js.org/#code/C4TwDgpgBAqgdgSwPZwNIRAZwDwBUB8UAvFANYZIBmUuUAPlABS0QAewEcAJpjVAPxkK1WgC4ocCADcIAJwCUAKEWhIUAAoIAxqQBMeADRRUUNh2694yNBhwFCJFu048+ggN5QA2uqgI4xgC64rg+gVAAvlDikjKyKuDQmjoAzIbGps4WQiBUNA58Zi68tB7evv5BIWGR0RLScsqq0ABiSEjEUJ4AhuKYwLL+AOZGAEZ9A8ORCWoAQu2dPfwTg3AjUONQ-atD04qUAK5wWsDWUJTtePiMCLriyXrYbR0AZDRGAOTdH-hGCCn3bSkNLPKBvXCfb74eTiKRIBBcLqKKAoqCKCLKAA2EGAUFYgJ0+lBDHmSEhPygAHpKV0oL0tpM1rUGD0VlMGEcuBBKP4IIiMdjcSACcCngsSe1yYRqbT6dsplEWXTlgydvQoJzubz+YogA),

it seems like `keyof T` gives more accurate result. (check `x` and `y` at the end)

**Comment by dragomirtitian** [comment]
Yeah, if it's not `keyof T` as a constraint to `K` the type is not homomorphic  anymore, we can get back to it being homomorphic if we use `Pick` again.

```ts

type UnionKeys<T> = keyof T | (T extends T ? keyof T : never)

type Pick2<T, K extends UnionKeys<T>> = T extends T ? Pick<T, K> : never
type Pick3<T, K extends keyof T> = T extends T ? { [P in K]: T[P] } : never

type Foo = { a: string, b: string }
type Boo = { a?: string, b: string }

function foo<T>(i2: Pick2<Foo & T, 'a'>, i3: Pick3<Foo & T, 'a'>): void {
    
}

let x: Pick2<Foo | Boo, 'a'> // Pick<Foo, "a"> | Pick<Boo, "a">
let y: Pick3<Foo | Boo, 'a'> // { a: string } | { a?: string | undefined }
```
[Playground](https://typescript-play.js.org/#code/C4TwDgpgBAqgdgSwPZwNIRAZwDwBUB8UAvFANYZIBmUuUAPlABS0QAewEcAJpjVAPxkK1WgC4ocCADcIAJwCUAKEWhIUAAoIAxqQBMeADRRUUNh2694yNBhwFCJFu048+gzTsPHC4yTNkq4NAepADMXiZmLrzkIFQ0DnxRFm5QAN5QANrqUAhwxgC64rjZBVAAvlC+0nLKqtAAYkhIxOlQAIbimMCyeQDmRgBGXT39FYFqAELNrRnt-CO9cANQw1DdS33jipQArnBawNZQlM14+IwIuuIh+k0tAGQ0RgDk7S-4RgihN9ph2PcoE9cK93vh5OIpEgEFx0oooAioIpysoADYQYBQVi-HR3GYMaZIUEfKAAelJGj+AOaRgARO1aYQGCFsIS6Qz8Ip0ZiQDj-oCCTSoG8SeS2p11qNlhV6OKFpLNrL9lwIJQ8hBYSigA)

**Comment by unional** [comment]
Yes, but that is just trying to push it down to get the type works again with `UnionKeys<>`.

For this usage, what is the benefit of using `UnionKeys<T>` vs `keyof T`?

I can't find an example that using `UnionKeys<T>` would be better than `keyof T` in this situation,
and since we are distributing the type anyway, it does not seem to be any performance benefits (in contrast to having a merged type vs union type, which the `T extends T ? { [P in K]: T[P] } : never` offers).

**Comment by dragomirtitian** [comment]
@unional  (Sorry saw the comment forgot to respond). 

I can't think of any concrete use cases where I would want to `Pick` from the un-common fields of a union. It is kind of neat you can write: 

```ts
type UnionKeys<T> = keyof T | (T extends T ? keyof T : never)

type Id<T> = {} & { [ P in keyof T]: T[P]} // just for esthetics
type Pick2<T, K extends UnionKeys<T>> = T extends T ?  Pick<T, Extract<K, keyof T>> : never

type Union = {
    type: "A",
    foo: string
} | {
    type: "B",
    foo: string
    bar: string
}

type PickedUnion = Id<Pick2<Union, "type" | "bar">>
//same as
type PickedUnionResult = {
    type: "A";
} | {
    type: "B";
    bar: string;
}
```
[Link](https://typescript-play.js.org/#code/C4TwDgpgBAqgdgSwPZwNIRAZwDwBUB8UAvFANYZIBmUuUAPlABS0QAewEcAJpjVAPxkK1WgC4ocCADcIAJwCUAKEWhIUAJJc8hEgG8AvlABkUXVADaUAApQEcISCo0AuuNzmrzwwHpvUAFYArpjAUJRIslAQIQAWEMAIAMaYKuDQVkmkAEx4ADRQqFHsnDywiCjoWNo6fGwc3Ly0gtaZeVAAouyyAIaJwNio+eSOIviE4pIyssqq0PDI9nqKUCtQs+IARACCG7nLq+FI4iGydgDmioYMuvsr61AbAEK7t2FIR1An568ARt2yx2ApzgF30MzSLUS5C48xQxA0WgyUJysLg+Q2sw29Aef1kGzGil8mG6AFtoN0UrNIdDUQAlaKBAA2oSWqzWaU2OwA3JdsTc2fcnhseWzcYDgWcefogA)

I think for `Omit` the case for omitting from just some members might be stronger but that is not based on anything just a  gut feeling.

**Comment by unional** [comment]
Thanks! That's a great example.
The `UnionKeys` make this usage possible. If using just `keyof T`, the `Pick2<>` will complain the `bar` is not a valid key.

Thanks for all your input and your continuous contribution to SO and to the community. 🌷

**Pull request merged**
